spring:
  datasource:
    url: jdbc:mysql://161.117.4.142:3907/integral_century_mart?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&maxReconnects=3&useSSL=false
    username: root
    password: ZzG#Mysql.$790703!^
