spring:
  datasource:
    url: jdbc:mysql://localhost/zhuangxiu?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    username: root
    password:  123456
    driver-class-name: com.mysql.jdbc.Driver